name: zaka-bounty CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


    # Set up the Node.js environment for the Fastify and Next.js apps
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

    #Set up the Rust enviroment for the Soroban Smart contracts
      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown


      - name: Install Node Dependencies
        run: npm install


      - name: Run Smart Contracts tests
       # we need to direct GitHub to the contracts directory
        working-directory: ./packages/contracts
        run: cargo test
    
      - name: Build Smart Contracts (WASM)
        working-directory: ./packages/contracts
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Build Web Packages (Turborepo)
       # Triggers the build for the frontend and backend
        run: npm run build